# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Menu',
        ),
        migrations.RenameField(
            model_name='mealtypeonmenu',
            old_name='date',
            new_name='menu',
        ),
        migrations.AddField(
            model_name='dishonmenu',
            name='name',
            field=models.CharField(default='dish', max_length=250),
        ),
        migrations.AddField(
            model_name='mealtypeonmenu',
            name='name',
            field=models.CharField(default='dish', max_length=250),
        ),
    ]
