# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-27 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0002_auto_20190427_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtypeonmenu',
            name='name',
            field=models.CharField(default='mealtype', max_length=250),
        ),
    ]
