# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-16 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0003_auto_20190427_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='dishonmenu',
            name='name',
            field=models.IntegerField(default=5),
        ),
    ]
