# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-24 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0004_auto_20190516_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='type',
        ),
        migrations.AlterField(
            model_name='dishonmenu',
            name='name',
            field=models.CharField(default='dish', max_length=250),
        ),
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
