# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-06 13:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0005_auto_20190624_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealtypeonmenu',
            old_name='name',
            new_name='n',
        ),
    ]
