# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-08 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jelovnik', '0007_auto_20190706_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtypeonmenu',
            name='date',
            field=models.CharField(default='1.1.2000.', max_length=100),
            preserve_default=False,
        ),
    ]
